version: '3.7'
services:
    app:
        build: .
        restart: on-failure
        volumes:
            - ./:/app
    nginx:
        image: nginx:alpine
        restart: on-failure
        ports:
            - 80:80
        volumes:
            - ./:/app
            - ./docker/nginx:/etc/nginx/conf.d
    node:
        image: node:slim
        tty: true
        working_dir: /app
        volumes:
            - ./:/app
    db:
        image: mariadb:latest
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - 3306:3306
        expose:
            - 5432
        volumes:
            - db:/var/lib/mysql
volumes:
    db: