version: '3.7'
services:
    app:
        build: .
        restart: on-failure
        volumes:
            - ./:/app
    nginx:
        image: nginx:alpine
        restart: on-failure
        ports:
            - 80:80
        volumes:
            - ./:/app
            - ./docker/nginx:/etc/nginx/conf.d
    node:
        image: node:slim
        tty: true
        working_dir: /app
        volumes:
            - ./:/app
    db:
        image: postgres:latest
        restart: on-failure
        environment:
            POSTGRES_PASSWORD: secret
        ports:
            - 5432:5432
        expose:
            - 5432
        volumes:
            - db:/var/lib/postgresql/data
volumes:
    db: