controllers:
    resource: ../../src/Controller/
    type: annotation

AplycaBlogControllers:
    resource: ../../src/Kevocde/AplycaBlog/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
